"""Initial migration with core tables

Revision ID: 346ba86e9c48
Revises: 
Create Date: 2025-08-12 17:57:40.940998

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '346ba86e9c48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('institution', sa.String(length=50), nullable=False),
    sa.Column('account_type', sa.Enum('CHECKING', 'SAVINGS', 'INVESTMENT',
                                        'CREDIT', 'LOAN', name='accounttype'),
              nullable=False),
    sa.Column('account_number_masked', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=50), nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VALIDATED', 'COMPLETED',
                                  'FAILED', name='importstatus'),
              nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('validation_notes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('transaction_type',
              sa.Enum('DEBIT', 'CREDIT', name='transactiontype'),
              nullable=False),
    sa.Column('import_session_id', sa.String(length=36), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['import_session_id'], ['import_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('import_sessions')
    op.drop_table('accounts')
    # ### end Alembic commands ###
